install:
 - source ./texlive.sh

cache:
  directories:
    - /tmp/texlive
    - /tmp/fontspec-test-fonts

stages:
 - test

jobs:
  include:
    - stage:  test
      name:   "XeTeX tests"
      script: l3build check -H --engine xetex  --shuffle --first 0-pkg-load || ( cat build/*/`ls -t  build/*/*.log | head -n1 | xargs basename | cut -f 1 -d . `.log && false )
    - script: l3build check -H --engine luatex --shuffle --first 0-pkg-load || ( cat build/*/`ls -t  build/*/*.log | head -n1 | xargs basename | cut -f 1 -d . `.log && false )
      name:   "LuaTeX tests"

