install:
 - source ./texlive.sh

cache:
  directories:
    - /tmp/texlive
    - /tmp/fontspec-test-fonts

script:
 - l3build check -H

jobs:
  include:
    - stage: trigger downstream
      jdk: oraclejdk8
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
          sh trigger-travis.sh wspr unicode-math $TRAVIS_ACCESS_TOKEN
        fi
